#!/usr/bin/env bash
# Export recent conversation context and memories to a markdown file
# that any Claude Code session can read. Run manually or on a cron.
#
# Usage: ./scripts/export-context.sh
# Output: store/shared-context.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DB="$PROJECT_ROOT/store/master-agent.db"
OUTPUT="$PROJECT_ROOT/store/shared-context.md"

if [ ! -f "$DB" ]; then
  echo "Database not found at $DB"
  exit 1
fi

cat > "$OUTPUT" << 'HEADER'
# Shared Context (auto-generated)
> Last updated at TIMESTAMP
> This file is auto-generated by scripts/export-context.sh
> It provides cross-session visibility into recent conversations and memories.

HEADER

# Replace timestamp
sed -i '' "s/TIMESTAMP/$(date '+%Y-%m-%d %H:%M:%S')/" "$OUTPUT"

echo "## Recent Conversations (last 10 exchanges)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

sqlite3 -markdown "$DB" "
  SELECT
    datetime(created_at, 'unixepoch', 'localtime') as time,
    role,
    CASE WHEN length(content) > 200 THEN substr(content, 1, 200) || '...' ELSE content END as content
  FROM conversation_log
  ORDER BY created_at DESC
  LIMIT 20;
" >> "$OUTPUT" 2>/dev/null || echo "_No conversations yet._" >> "$OUTPUT"

echo "" >> "$OUTPUT"
echo "## Active Memories" >> "$OUTPUT"
echo "" >> "$OUTPUT"

sqlite3 -markdown "$DB" "
  SELECT
    sector,
    content,
    round(salience, 2) as salience,
    datetime(accessed_at, 'unixepoch', 'localtime') as last_accessed
  FROM memories
  WHERE salience > 0.3
  ORDER BY salience DESC, accessed_at DESC
  LIMIT 15;
" >> "$OUTPUT" 2>/dev/null || echo "_No memories yet._" >> "$OUTPUT"

echo "" >> "$OUTPUT"
echo "## Scheduled Tasks" >> "$OUTPUT"
echo "" >> "$OUTPUT"

sqlite3 -markdown "$DB" "
  SELECT
    id,
    substr(prompt, 1, 80) as prompt,
    schedule,
    status,
    datetime(next_run, 'unixepoch', 'localtime') as next_run
  FROM scheduled_tasks
  ORDER BY next_run;
" >> "$OUTPUT" 2>/dev/null || echo "_No scheduled tasks._" >> "$OUTPUT"

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "_Run \`/context\` in any Claude Code session for a live query._" >> "$OUTPUT"

echo "Context exported to $OUTPUT"
