#!/usr/bin/env bash
# Generate src/version.ts with git hash and build timestamp
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION=$(node -p "require('./package.json').version")
GIT_HASH=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$ROOT/src/version.ts" << EOF
// Auto-generated by scripts/generate-version.sh -- do not edit
export const VERSION = '${VERSION}';
export const GIT_HASH = '${GIT_HASH}';
export const BUILD_TIME = '${BUILD_TIME}';
export const BUILD_STRING = \`v\${VERSION}+\${GIT_HASH}\`;
EOF

# Also write a plain JSON for easy reading by /rebuild before restart
mkdir -p "$ROOT/dist"
cat > "$ROOT/dist/build-info.json" << EOF
{"version":"${VERSION}","gitHash":"${GIT_HASH}","buildTime":"${BUILD_TIME}"}
EOF
